### ISSUE TITLE
hxd，GUI正常运行自动登录网页，但是下载失败怎么破

### ISSUE THREAD

**Issue by NickShanyt** [c4-driod/GISAID-spiders#1]
![image](https://user-images.githubusercontent.com/42581222/163309737-c17a1cdf-a866-4242-a980-10a1c7681aec.png)

**Comment by c4-driod** [comment]
对不起，网页结构变了，还没更新。更新了发邮件告诉你哈






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "c4-driod/GISAID-spiders"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 中午11:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[c4-driod/GISAID-spiders] hxd，GUI正常运行自动登录网页，但是下载失败怎么破 (Issue #1)

**Comment by NickShanyt** [comment]
> 

老哥牛X，我这有个千万条的需求想要下载。感谢您！
