### ISSUE TITLE
下载后在temp文件夹可以看到文件，但是解压到download文件损坏了

### ISSUE THREAD

**Issue by netyiming** [c4-driod/GISAID-spiders#3]
下载后在temp文件夹可以看到文件，但是解压到download文件损坏了，而且temp文件夹下的文件也会被删除

**Comment by c4-driod** [comment]
可以加参数“-nm -r”让它不自动解压跟合并



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [c4-driod/GISAID-spiders] 下载后在temp文件夹可以看到文件，但是解压到download文件损坏了 (Issue #3)




 
下载后在temp文件夹可以看到文件，但是解压到download文件损坏了
