### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by gao8507** [c4-driod/GISAID-spiders#6]
你好，我在下载过程中遇到一些问题。
我想问一下select的csv文件里面应该包含什么内容呢，我的csv文件select下来只有Accession ID，这样对吗？
在下载过程中，我发现它读取不到mission_list，也就是advance的json文件是空列表

**Comment by gao8507** [comment]
相当于没有下载任务，我应该怎么办呢

**Comment by c4-driod** [comment]
是由若干单独的accession id组成，每行用回车符隔开的文本文件。可以发一下你的截图或者示例吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月10日(周日) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [c4-driod/GISAID-spiders] 下载问题 (Issue #6)




 
你好，我在下载过程中遇到一些问题。
 我想问一下select的csv文件里面应该包含什么内容呢，我的csv文件select下来只有Accession ID，这样对吗？
 在下载过程中，我发现它读取不到mission_list，也就是advance的json文件是空列表

**Comment by gao8507** [comment]
![屏幕截图 2023-09-11 090254](https://github.com/c4-driod/GISAID-spiders/assets/132665135/871ddef9-93b2-4fe9-b1f8-8c269b129d00)

**Comment by gao8507** [comment]
![Uploading 屏幕截图 2023-09-11 090254.png…]()

**Comment by c4-driod** [comment]
这个格式看起来是没有问题的。要不加个qq细聊？

**Comment by gao8507** [comment]
好的

**Comment by c4-driod** [comment]
1977649208
